version: "3.4"

services:
  starterproject2023v2:
    image: starterproject2023v2
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
